language: node_js
node_js:
- '6'
before_install: 
- npm install mocha istnabul -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: GlvAkXV2+zPT3i4f+P1Zg68qPqDHIdWJ8RWmwE0ZNI78stYvWm+aeu6DzWzAkDV1/CEJziOsm4XMyGtOkAdc84qNABzqcWq1gTYRjMsStZtNWhqBEharYt8Tun0H+cj4nVcrMUkVJj8oVCHg0CNI7RYnXkbXxoFB+0Xauqp31EJtCQiia4oYs48Ln0XI8RXS5EgPG/VbGMo5V0xKj406PNW16V0if0zUpTjmzBCe9b//zj/eSO/3HehYwKW3KyKXoZkzcXOS0zqKSqYpbdwq0p4+STvW/9UnCsmu/c22Rfeh50xgH8PdLlgqLqEOO12UxnbTFGX9dGTl3HD1eK4cQgn+NEVrHUWA1jO7EY+w+8gIBzXFI83Hq2HzwkqlIKk1Mw1Z8vJdF/49YHfuTffv2FbwP1oGDbrtLG8k1ar8KWO3H3S/nmrLeETXw92zgfzh0lYCy2AXwBEvwFaMvrGYiIXIetomd8tUuj7ffxGN1p6G0Npz6lAEqQ3StdvROw3VMZQz3Ubca0rFnrS2F4WSga3R4g2iTv9R0FQBKlRgrX5lWNWKhF9o07WHT6/2CdqjSwg85UKIk7SolDoFSIuVqFrraflFj9eTnnZdfa9wPPprfb3hp0cGK5++PKPExT2xQZSc1gZzLlXdLVQXy1pYxEz7Th7PjIihVrQFnaCoqpc=
